# Generated by Django 3.2.6 on 2021-08-20 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_member_member_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='account_owner',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
