# Generated by Django 3.2.7 on 2021-09-17 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('profile_setup', 'Profile Setup'), ('update_information', 'Update Information'), ('login_issues', 'Login Issues'), ('billing_payment', 'Billing/Payment'), ('predictive_model', 'Predictive Model'), ('email_inbox', 'Email Inbox'), ('data_issue', 'Data Issue(s)'), ('website_related', 'Website Related'), ('other', 'Other')], max_length=100)),
                ('other_subject', models.CharField(max_length=100, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='message_attachments')),
                ('message', models.TextField()),
                ('send_date', models.DateTimeField(auto_now_add=True)),
                ('is_seen', models.BooleanField(blank=True, default=False, null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('reply', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='message_replies', to='messages_app.membermessages')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'member_messages',
            },
        ),
    ]
