# Generated by Django 3.2.7 on 2021-09-17 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messages_app', '0002_alter_membermessages_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membermessages',
            name='other_subject',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='membermessages',
            name='subject',
            field=models.CharField(blank=True, choices=[('profile_setup', 'Profile Setup'), ('update_information', 'Update Information'), ('login_issues', 'Login Issues'), ('billing_payment', 'Billing/Payment'), ('predictive_model', 'Predictive Model'), ('email_inbox', 'Email Inbox'), ('data_issue', 'Data Issue(s)'), ('website_related', 'Website Related'), ('other', 'Other')], max_length=100, null=True),
        ),
    ]
