# Generated by Django 3.2.7 on 2021-09-17 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messages_app', '0003_auto_20210917_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membermessages',
            name='reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_replies', to='messages_app.membermessages'),
        ),
    ]
