# Generated by Django 2.2 on 2021-04-13 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_stripe_id', models.CharField(max_length=100, unique=True)),
                ('invoice_pdf_url', models.URLField(max_length=255, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'invoices',
            },
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_stripe_id', models.CharField(max_length=100, unique=True)),
                ('invoice_stripe_id', models.CharField(max_length=100, null=True, unique=True)),
                ('receipt_pdf_url', models.URLField(max_length=255, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'transactions',
            },
        ),
    ]
