# Generated by Django 3.2.7 on 2021-10-04 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0004_charges_is_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charges',
            name='invoice_id',
        ),
    ]
