# Generated by Django 3.2.7 on 2021-09-26 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('membership_type', models.CharField(blank=True, choices=[('starter', 'Starter'), ('professional', 'Professional'), ('expert', 'Expert'), ('starter_monthly', 'Starter Monthly'), ('starter_yearly', 'Starter Yearly'), ('professional_monthly', 'Professional Monthly'), ('professional_yearly', 'Professional Yearly'), ('expert_monthly', 'Expert Monthly'), ('expert_yearly', 'Expert Yearly'), ('unlimited', 'Unlimited (development)')], max_length=30, null=True)),
                ('monthly_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('yearly_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('day_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stripe_plane_id', models.CharField(blank=True, max_length=100, null=True)),
                ('stripe_price_id', models.CharField(blank=True, max_length=100, null=True)),
                ('additional_fee_per_extra_record', models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True)),
                ('allowed_records_count', models.BigIntegerField(blank=True, null=True)),
                ('parent', models.CharField(blank=True, choices=[('starter', 'Starter'), ('professional', 'Professional'), ('expert', 'Expert'), ('unlimited_development', 'Unlimited (Development)')], max_length=30, null=True)),
                ('range_label', models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=20, null=True)),
            ],
            options={
                'db_table': 'membership',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_customer_id', models.CharField(blank=True, max_length=100, null=True)),
                ('stripe_card_token', models.CharField(blank=True, max_length=200, null=True)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=60, null=True)),
                ('subscription_status', models.BooleanField(blank=True, null=True)),
                ('subscription_period_start', models.DateTimeField(blank=True, null=True)),
                ('subscription_period_end', models.DateTimeField(blank=True, null=True)),
                ('card_expire', models.DateTimeField(blank=True, null=True)),
                ('stripe_card_id', models.CharField(blank=True, max_length=50, null=True)),
                ('last_invoice_id', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'subscriptions',
            },
        ),
    ]
