# Generated by Django 3.2.3 on 2021-05-29 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0004_charges'),
    ]

    operations = [
        migrations.AddField(
            model_name='charges',
            name='amount',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
