# Generated by Django 3.2.3 on 2021-05-29 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0005_charges_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='charges',
            name='invoice_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
