# Generated by Django 3.2.3 on 2021-05-29 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0006_charges_invoice_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='charges',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
