# Generated by Django 3.2.3 on 2021-05-29 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0007_charges_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charges',
            name='invoice_token',
        ),
    ]
