# Generated by Django 3.2.6 on 2021-08-09 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0009_auto_20210809_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='membership_type',
            field=models.CharField(blank=True, choices=[('starter', 'Starter'), ('professional', 'Professional'), ('expert', 'Expert'), ('starter_monthly', 'Starter Monthly'), ('starter_yearly', 'Starter Yearly'), ('professional_monthly', 'Professional Monthly'), ('professional_yearly', 'Professional Yearly'), ('expert_monthly', 'Expert Monthly'), ('expert_yearly', 'Expert Yearly'), ('unlimited', 'Unlimited (development)')], max_length=30, null=True),
        ),
    ]
