# Generated by Django 3.2.4 on 2021-06-25 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CrashReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('title', models.CharField(max_length=150)),
                ('extra_notes', models.TextField()),
                ('file_attachment', models.FileField(blank=True, null=True, upload_to='crash_reports/files')),
                ('screenshot', models.FileField(blank=True, null=True, upload_to='crash_reports/screenshots')),
                ('is_seen', models.BooleanField(default=False)),
                ('is_solved', models.BooleanField(default=False)),
                ('crash_status', models.CharField(blank=True, choices=[('not_fixed', 'Not Fixed'), ('fixed', 'Fixed'), ('in_process', 'In Process')], default='not_fixed', max_length=20, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bug_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'crash_reports',
            },
        ),
    ]
