# Generated by Django 3.2.7 on 2021-09-26 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrashReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, null=True)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('file_attachment', models.FileField(blank=True, null=True, upload_to='crash_reports/files')),
                ('screenshot', models.FileField(blank=True, null=True, upload_to='crash_reports/screenshots')),
                ('is_seen', models.BooleanField(default=False)),
                ('is_solved', models.BooleanField(default=False)),
                ('crash_status', models.CharField(blank=True, choices=[('not_fixed', 'Not Fixed'), ('fixed', 'Fixed'), ('in_progress', 'In Progress')], default='not_fixed', max_length=20, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'crash_reports',
            },
        ),
    ]
