# Generated by Django 3.2.4 on 2021-06-25 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crash_reporting', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crashreport',
            old_name='extra_notes',
            new_name='description',
        ),
    ]
