# Generated by Django 3.2.7 on 2021-09-26 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crash_reporting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crashreport',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bug_reports', to=settings.AUTH_USER_MODEL),
        ),
    ]
