# Generated by Django 3.2.4 on 2021-06-29 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crash_reporting', '0002_rename_extra_notes_crashreport_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crashreport',
            name='crash_status',
            field=models.CharField(blank=True, choices=[('not_fixed', 'Not Fixed'), ('fixed', 'Fixed'), ('in_progress', 'In Progress')], default='not_fixed', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='crashreport',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
