from django.urls import path, re_path, include
from .views import *

urlpatterns = [
    # path("list", DataListView.as_view(), name="data-list"),
    path("init", data_handler_init, name="data-handler-init"),
    re_path("^upload/(?P<filename>[^/]+)$", DataHandlerFileUpload.as_view(), name="data-handler-upload"),
    path("download/report/<str:report_type>/<int:run_history_id>", download_report_file,
         name='data-handler-download-pdf-report'),
    path("api/", include([
        path("save-columns", SaveColumnsView.as_view(), name="data-handler-save-columns-names"),
        path("get-columns", GetColumnsView.as_view(), name="data-handler-get-columns"),
        path("get-all-columns", GetAllColumnsView.as_view(), name="data-handler-get-all-columns"),
        path("rows", GetRowsView.as_view(), name="data-handler-rows"),
        path("search-query-records", GetRowsBySearchQueryView.as_view(), name="data-handler-search-rows"),
        path("not-validate-rows", NotValidateRowsView.as_view(), name="data-handler-not-validate-rows"),
        path("update-rows", SaveNewRowsUpdateView.as_view(), name="data-handler-update-rows"),
        path("delete-file", DeleteDataFileView.as_view(), name="data-handler-delete-file"),
        path("validate-columns", ValidateColumnsView.as_view(), name="data-handler-validate-columns"),
        path("fetch-last-page-info", FetchLastPageInfoView.as_view(), name="data-handler-fetch-last-page-info"),
        path("not-validate-columns", NotValidateColumnsView.as_view(), name="data-handler-not-validate-columns"),
        path("filter-rows", FilterRowsView.as_view(), name="data-handler-filter-rows"),
        path("accepts-download", AcceptsDownload.as_view(), name="data-handler-accepts-download"),
        path("check-upload-member", CheckMemberUpload.as_view(), name="data-handler-check-upload-member"),
        path("check-process-status", CheckMemberProcessStatus.as_view(), name="data-handler-check-process-status"),
        path("fetch-last-session-name", FetchLastSessionNameView.as_view(),
             name="data-handler-fetch-last-session-name"),
        path("check-user-records-number", CheckMemberRecordNumber.as_view(),
             name="data-handler-user-check-record-number"),
        path("set-last-session-name", SetLastSessionName.as_view(), name="data-handler-set-last-session-name"),
        path("set-session-label", SetSessionLabel.as_view(), name="data-handler-set-session-label"),
        path("delete-data-session", DeleteSessionView.as_view(), name="data-handler-delete-session"),
        path("rename-data-session", RenameSessionView.as_view(), name="data-handler-rename-session"),
        path("check-valid-data", CheckValidDataView.as_view(), name="data-handler-check-valid-data"),
        path("fetch-data-session-info", FetchDataSessionInfoView.as_view(), name="data-handler-fetch-data-session"),
        path("fetch-table-overview", FetchTableOverviewDataView.as_view(), name="data-handler-fetch-table-overview"),
        path("get-table-pagination", GetTablePagination.as_view(), name="data-handler-pagination"),
        path("check-is-allowed-run-model", IsAllowedToRunModel.as_view(), name="data-handler-check-allowed-run-model"),
        path("check-session-dtype-valid", CheckIfSessionDataTypeValid.as_view(), name="data-handler-check-dtype-valid"),
        path("export", ExportUpdatedDataFile.as_view(), name="data-handler-export-updated-file"),
        path("fetch-session-dashboard-session", FetchDashboardSessionData.as_view(),
             name="data-handler-fetch-dashboard-session"),
    ])),

]
