# Generated by Django 2.2 on 2021-04-13 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed_records_count', models.IntegerField(blank=True, null=True)),
                ('join_date', models.DateTimeField(auto_now_add=True)),
                ('has_sessions', models.BooleanField(default=False)),
                ('last_uploaded_session', models.IntegerField(blank=True, null=True)),
                ('is_run_the_model', models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                'db_table': 'member_data_files',
            },
        ),
        migrations.CreateModel(
            name='DataHandlerSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_upload_procedure', models.CharField(blank=True, choices=[('local_file', 'Local File'), ('google_plus', 'Google Plus'), ('one_drive', 'One Drive'), ('dropbox', 'Dropbox'), ('none', 'None')], max_length=20, null=True)),
                ('data_file_path', models.CharField(blank=True, max_length=255, null=True)),
                ('base_data_file_path', models.CharField(blank=True, max_length=255, null=True)),
                ('donation_columns', models.CharField(blank=True, max_length=255, null=True)),
                ('current_session_name', models.CharField(blank=True, choices=[('upload', 'Upload'), ('pick_columns', 'Pick Columns'), ('data_process', 'Data Processing'), ('run_modal', 'Run Predictive Modal')], max_length=70, null=True)),
                ('run_modal_date_time', models.CharField(blank=True, max_length=60, null=True)),
                ('data_handler_session_label', models.CharField(blank=True, max_length=70, null=True)),
                ('selected_columns', models.TextField(blank=True, null=True)),
                ('selected_columns_dtypes', models.TextField(blank=True, null=True)),
                ('donor_id_column', models.CharField(blank=True, max_length=150)),
                ('is_donor_id_selected', models.BooleanField(blank=True, default=False, null=True)),
                ('unique_id_column', models.CharField(blank=True, max_length=200, null=True)),
                ('all_columns_with_dtypes', models.TextField(blank=True, null=True)),
                ('is_process_complete', models.BooleanField(blank=True, default=False, null=True)),
                ('all_records_count', models.BigIntegerField(blank=True, null=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('file_name', models.CharField(blank=True, max_length=50, null=True)),
                ('pdf_report_file_path', models.CharField(blank=True, max_length=255, null=True)),
                ('csv_report_file_path', models.CharField(blank=True, max_length=255, null=True)),
                ('is_validate_data', models.BooleanField(blank=True, null=True)),
                ('not_validate_columns', models.CharField(blank=True, max_length=255, null=True)),
                ('geo_columns', models.CharField(blank=True, max_length=255, null=True)),
                ('above_plan_limit_records', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'data_handler_sessions',
            },
        ),
        migrations.CreateModel(
            name='MemberDownloadCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_accept_terms', models.BooleanField(blank=True, default=False, null=True)),
                ('is_accept_download_template', models.BooleanField(blank=True, default=False, null=True)),
                ('is_download_template', models.BooleanField(blank=True, default=False, null=True)),
                ('download_counter', models.IntegerField(blank=True, default=0, null=True)),
                ('date_inserted', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'members_download_counter',
            },
        ),
        migrations.CreateModel(
            name='RunHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('session_name', models.CharField(blank=True, max_length=100, null=True)),
                ('run_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('pdf_report_file_path', models.CharField(blank=True, max_length=200, null=True)),
                ('csv_report_file_path', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
