# Generated by Django 2.2 on 2021-04-13 20:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data_handler', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='runhistory',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='runhistory',
            name='session_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='run_history', to='data_handler.DataHandlerSession'),
        ),
        migrations.AddField(
            model_name='memberdownloadcounter',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='download_counter', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='datahandlersession',
            name='data_handler_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_sessions_set', to='data_handler.DataFile'),
        ),
        migrations.AddField(
            model_name='datafile',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_data_file', to=settings.AUTH_USER_MODEL),
        ),
    ]
