# Generated by Django 3.2.7 on 2021-09-26 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data_handler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='runhistory',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='member_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='runhistory',
            name='session_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='run_history', to='data_handler.datahandlersession'),
        ),
        migrations.AddField(
            model_name='modelmostsimilarfile',
            name='data_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='data_session_model_similar_files', to='data_handler.datahandlersession'),
        ),
        migrations.AddField(
            model_name='modelmostsimilarfile',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='member_model_similar_files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='memberdownloadcounter',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='download_counter', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='datausage',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_usage', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='datahandlersession',
            name='data_handler_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_sessions_set', to='data_handler.datafile'),
        ),
        migrations.AddField(
            model_name='datafile',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_data_file', to=settings.AUTH_USER_MODEL),
        ),
    ]
