# Generated by Django 2.2 on 2021-04-15 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_handler', '0002_auto_20210413_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runhistory',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='member_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='runhistory',
            name='session_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='run_history', to='data_handler.DataHandlerSession'),
        ),
    ]
