# Generated by Django 3.2 on 2021-04-25 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_handler', '0003_auto_20210415_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='datahandlersession',
            name='is_run_model',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
