# Generated by Django 3.2.2 on 2021-05-10 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_handler', '0005_auto_20210510_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datahandlersession',
            name='data_handler_session_label',
            field=models.CharField(blank=True, default='Default Name For this session', max_length=70, null=True),
        ),
    ]
