# Generated by Django 3.2.3 on 2021-05-22 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_handler', '0008_alter_datausage_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datahandlersession',
            name='all_records_count',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
