# Generated by Django 3.2.3 on 2021-05-22 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_handler', '0009_alter_datahandlersession_all_records_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datausage',
            name='created_at',
        ),
        migrations.AddField(
            model_name='datausage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
