# Generated by Django 3.2.5 on 2021-07-26 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_handler', '0010_auto_20210522_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='runhistory',
            name='modal_output_json_file_path',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
