# Generated by Django 3.2.5 on 2021-07-30 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_handler', '0011_runhistory_modal_output_json_file_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datahandlersession',
            name='base_data_file_path',
        ),
    ]
