# Generated by Django 3.2.5 on 2021-08-01 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_handler', '0012_remove_datahandlersession_base_data_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='datahandlersession',
            name='text_columns',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
