# Generated by Django 3.2.6 on 2021-08-06 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_handler', '0013_datahandlersession_text_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='datahandlersession',
            name='numeric_columns',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
