# Generated by Django 3.2.6 on 2021-08-07 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_handler', '0015_modelmostsimilarfile'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='modelmostsimilarfile',
            table='model_most_similar_file',
        ),
    ]
