# Generated by Django 3.2.6 on 2021-08-07 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_handler', '0016_alter_modelmostsimilarfile_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelmostsimilarfile',
            old_name='similar_value',
            new_name='similar_percentage',
        ),
    ]
