# Generated by Django 3.2.6 on 2021-08-07 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_handler', '0017_rename_similar_value_modelmostsimilarfile_similar_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelmostsimilarfile',
            name='feature_count',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='modelmostsimilarfile',
            name='unique_features',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
