# Generated by Django 3.2.6 on 2021-08-07 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_handler', '0018_auto_20210807_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelmostsimilarfile',
            name='categorical_data',
            field=models.CharField(default='[]', max_length=255),
        ),
    ]
