# Generated by Django 3.2.6 on 2021-08-09 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_handler', '0023_alter_modelmostsimilarfile_similar_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelmostsimilarfile',
            name='counter',
            field=models.PositiveBigIntegerField(default=1),
        ),
    ]
